insert into education_states (
  state_code,
  state_name,
  block_unit_name,
  block_officer_title,
  district_officer_title,
  udise_block_digits
) values
('01', 'Jammu and Kashmir', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('02', 'Himachal Pradesh', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('03', 'Punjab', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('04', 'Chandigarh', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('05', 'Uttarakhand', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('06', 'Haryana', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('07', 'Delhi', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('08', 'Rajasthan', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('09', 'Uttar Pradesh', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('10', 'Bihar', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('11', 'Sikkim', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('12', 'Arunachal Pradesh', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('13', 'Nagaland', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('14', 'Manipur', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('15', 'Mizoram', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('16', 'Tripura', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('17', 'Meghalaya', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('18', 'Assam', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('19', 'West Bengal', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('20', 'Jharkhand', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('21', 'Odisha', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('22', 'Chhattisgarh', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('23', 'Madhya Pradesh', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('24', 'Gujarat', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('25', 'Daman and Diu', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('26', 'Dadra and Nagar Haveli', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('27', 'Maharashtra', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('28', 'Andhra Pradesh', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('29', 'Karnataka', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('30', 'Goa', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('31', 'Lakshadweep', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('32', 'Kerala', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('33', 'Tamil Nadu', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('34', 'Puducherry', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('35', 'Andaman and Nicobar Islands', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('36', 'Telangana', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2),
('37', 'Ladakh', 'Block', 'Block-level MIS / education authority', 'District-level MIS / education authority', 2)
on conflict (state_code) do update set
  state_name = excluded.state_name,
  block_unit_name = excluded.block_unit_name,
  block_officer_title = excluded.block_officer_title,
  district_officer_title = excluded.district_officer_title,
  udise_block_digits = excluded.udise_block_digits;
