/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrincipalIndexRouteImport } from './routes/principal.index'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as LearnerIndexRouteImport } from './routes/learner.index'
import { Route as HodIndexRouteImport } from './routes/hod.index'
import { Route as DietIndexRouteImport } from './routes/diet.index'
import { Route as DeoIndexRouteImport } from './routes/deo.index'
import { Route as BeoIndexRouteImport } from './routes/beo.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PrincipalRoiRouteImport } from './routes/principal.roi'
import { Route as PrincipalHeatmapRouteImport } from './routes/principal.heatmap'
import { Route as PrincipalDashboardRouteImport } from './routes/principal.dashboard'
import { Route as PlatformTenantsRouteImport } from './routes/platform.tenants'
import { Route as PlatformOfficersRouteImport } from './routes/platform.officers'
import { Route as PlatformCreateRouteImport } from './routes/platform.create'
import { Route as LearnerWorkshopRouteImport } from './routes/learner.workshop'
import { Route as LearnerSandboxRouteImport } from './routes/learner.sandbox'
import { Route as LearnerPracticeRouteImport } from './routes/learner.practice'
import { Route as LearnerLearningRouteImport } from './routes/learner.learning'
import { Route as LearnerDashboardRouteImport } from './routes/learner.dashboard'
import { Route as LearnerCheckRouteImport } from './routes/learner.check'
import { Route as LearnerAssessmentRouteImport } from './routes/learner.assessment'
import { Route as HodDashboardRouteImport } from './routes/hod.dashboard'
import { Route as HodAnalyticsRouteImport } from './routes/hod.analytics'
import { Route as DietOverviewRouteImport } from './routes/diet.overview'
import { Route as DeoOverviewRouteImport } from './routes/deo.overview'
import { Route as BeoOverviewRouteImport } from './routes/beo.overview'
import { Route as AdminReadinessRouteImport } from './routes/admin.readiness'
import { Route as AdminPeopleRouteImport } from './routes/admin.people'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminMaturityRouteImport } from './routes/admin.maturity'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminCompletionRouteImport } from './routes/admin.completion'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalIndexRoute = PrincipalIndexRouteImport.update({
  id: '/principal/',
  path: '/principal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerIndexRoute = LearnerIndexRouteImport.update({
  id: '/learner/',
  path: '/learner/',
  getParentRoute: () => rootRouteImport,
} as any)
const HodIndexRoute = HodIndexRouteImport.update({
  id: '/hod/',
  path: '/hod/',
  getParentRoute: () => rootRouteImport,
} as any)
const DietIndexRoute = DietIndexRouteImport.update({
  id: '/diet/',
  path: '/diet/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeoIndexRoute = DeoIndexRouteImport.update({
  id: '/deo/',
  path: '/deo/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeoIndexRoute = BeoIndexRouteImport.update({
  id: '/beo/',
  path: '/beo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalRoiRoute = PrincipalRoiRouteImport.update({
  id: '/principal/roi',
  path: '/principal/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalHeatmapRoute = PrincipalHeatmapRouteImport.update({
  id: '/principal/heatmap',
  path: '/principal/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalDashboardRoute = PrincipalDashboardRouteImport.update({
  id: '/principal/dashboard',
  path: '/principal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformTenantsRoute = PlatformTenantsRouteImport.update({
  id: '/platform/tenants',
  path: '/platform/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformOfficersRoute = PlatformOfficersRouteImport.update({
  id: '/platform/officers',
  path: '/platform/officers',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformCreateRoute = PlatformCreateRouteImport.update({
  id: '/platform/create',
  path: '/platform/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerWorkshopRoute = LearnerWorkshopRouteImport.update({
  id: '/learner/workshop',
  path: '/learner/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerSandboxRoute = LearnerSandboxRouteImport.update({
  id: '/learner/sandbox',
  path: '/learner/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerPracticeRoute = LearnerPracticeRouteImport.update({
  id: '/learner/practice',
  path: '/learner/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerLearningRoute = LearnerLearningRouteImport.update({
  id: '/learner/learning',
  path: '/learner/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerDashboardRoute = LearnerDashboardRouteImport.update({
  id: '/learner/dashboard',
  path: '/learner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerCheckRoute = LearnerCheckRouteImport.update({
  id: '/learner/check',
  path: '/learner/check',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerAssessmentRoute = LearnerAssessmentRouteImport.update({
  id: '/learner/assessment',
  path: '/learner/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const HodDashboardRoute = HodDashboardRouteImport.update({
  id: '/hod/dashboard',
  path: '/hod/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HodAnalyticsRoute = HodAnalyticsRouteImport.update({
  id: '/hod/analytics',
  path: '/hod/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DietOverviewRoute = DietOverviewRouteImport.update({
  id: '/diet/overview',
  path: '/diet/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DeoOverviewRoute = DeoOverviewRouteImport.update({
  id: '/deo/overview',
  path: '/deo/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const BeoOverviewRoute = BeoOverviewRouteImport.update({
  id: '/beo/overview',
  path: '/beo/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReadinessRoute = AdminReadinessRouteImport.update({
  id: '/admin/readiness',
  path: '/admin/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/admin/people',
  path: '/admin/people',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMaturityRoute = AdminMaturityRouteImport.update({
  id: '/admin/maturity',
  path: '/admin/maturity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompletionRoute = AdminCompletionRouteImport.update({
  id: '/admin/completion',
  path: '/admin/completion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/completion': typeof AdminCompletionRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/maturity': typeof AdminMaturityRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/beo/overview': typeof BeoOverviewRoute
  '/deo/overview': typeof DeoOverviewRoute
  '/diet/overview': typeof DietOverviewRoute
  '/hod/analytics': typeof HodAnalyticsRoute
  '/hod/dashboard': typeof HodDashboardRoute
  '/learner/assessment': typeof LearnerAssessmentRoute
  '/learner/check': typeof LearnerCheckRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/learning': typeof LearnerLearningRoute
  '/learner/practice': typeof LearnerPracticeRoute
  '/learner/sandbox': typeof LearnerSandboxRoute
  '/learner/workshop': typeof LearnerWorkshopRoute
  '/platform/create': typeof PlatformCreateRoute
  '/platform/officers': typeof PlatformOfficersRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/principal/dashboard': typeof PrincipalDashboardRoute
  '/principal/heatmap': typeof PrincipalHeatmapRoute
  '/principal/roi': typeof PrincipalRoiRoute
  '/admin/': typeof AdminIndexRoute
  '/beo/': typeof BeoIndexRoute
  '/deo/': typeof DeoIndexRoute
  '/diet/': typeof DietIndexRoute
  '/hod/': typeof HodIndexRoute
  '/learner/': typeof LearnerIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/principal/': typeof PrincipalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/completion': typeof AdminCompletionRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/maturity': typeof AdminMaturityRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/beo/overview': typeof BeoOverviewRoute
  '/deo/overview': typeof DeoOverviewRoute
  '/diet/overview': typeof DietOverviewRoute
  '/hod/analytics': typeof HodAnalyticsRoute
  '/hod/dashboard': typeof HodDashboardRoute
  '/learner/assessment': typeof LearnerAssessmentRoute
  '/learner/check': typeof LearnerCheckRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/learning': typeof LearnerLearningRoute
  '/learner/practice': typeof LearnerPracticeRoute
  '/learner/sandbox': typeof LearnerSandboxRoute
  '/learner/workshop': typeof LearnerWorkshopRoute
  '/platform/create': typeof PlatformCreateRoute
  '/platform/officers': typeof PlatformOfficersRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/principal/dashboard': typeof PrincipalDashboardRoute
  '/principal/heatmap': typeof PrincipalHeatmapRoute
  '/principal/roi': typeof PrincipalRoiRoute
  '/admin': typeof AdminIndexRoute
  '/beo': typeof BeoIndexRoute
  '/deo': typeof DeoIndexRoute
  '/diet': typeof DietIndexRoute
  '/hod': typeof HodIndexRoute
  '/learner': typeof LearnerIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/principal': typeof PrincipalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/completion': typeof AdminCompletionRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/maturity': typeof AdminMaturityRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/beo/overview': typeof BeoOverviewRoute
  '/deo/overview': typeof DeoOverviewRoute
  '/diet/overview': typeof DietOverviewRoute
  '/hod/analytics': typeof HodAnalyticsRoute
  '/hod/dashboard': typeof HodDashboardRoute
  '/learner/assessment': typeof LearnerAssessmentRoute
  '/learner/check': typeof LearnerCheckRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/learning': typeof LearnerLearningRoute
  '/learner/practice': typeof LearnerPracticeRoute
  '/learner/sandbox': typeof LearnerSandboxRoute
  '/learner/workshop': typeof LearnerWorkshopRoute
  '/platform/create': typeof PlatformCreateRoute
  '/platform/officers': typeof PlatformOfficersRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/principal/dashboard': typeof PrincipalDashboardRoute
  '/principal/heatmap': typeof PrincipalHeatmapRoute
  '/principal/roi': typeof PrincipalRoiRoute
  '/admin/': typeof AdminIndexRoute
  '/beo/': typeof BeoIndexRoute
  '/deo/': typeof DeoIndexRoute
  '/diet/': typeof DietIndexRoute
  '/hod/': typeof HodIndexRoute
  '/learner/': typeof LearnerIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/principal/': typeof PrincipalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/completion'
    | '/admin/config'
    | '/admin/content'
    | '/admin/departments'
    | '/admin/maturity'
    | '/admin/overview'
    | '/admin/people'
    | '/admin/readiness'
    | '/beo/overview'
    | '/deo/overview'
    | '/diet/overview'
    | '/hod/analytics'
    | '/hod/dashboard'
    | '/learner/assessment'
    | '/learner/check'
    | '/learner/dashboard'
    | '/learner/learning'
    | '/learner/practice'
    | '/learner/sandbox'
    | '/learner/workshop'
    | '/platform/create'
    | '/platform/officers'
    | '/platform/tenants'
    | '/principal/dashboard'
    | '/principal/heatmap'
    | '/principal/roi'
    | '/admin/'
    | '/beo/'
    | '/deo/'
    | '/diet/'
    | '/hod/'
    | '/learner/'
    | '/platform/'
    | '/principal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/completion'
    | '/admin/config'
    | '/admin/content'
    | '/admin/departments'
    | '/admin/maturity'
    | '/admin/overview'
    | '/admin/people'
    | '/admin/readiness'
    | '/beo/overview'
    | '/deo/overview'
    | '/diet/overview'
    | '/hod/analytics'
    | '/hod/dashboard'
    | '/learner/assessment'
    | '/learner/check'
    | '/learner/dashboard'
    | '/learner/learning'
    | '/learner/practice'
    | '/learner/sandbox'
    | '/learner/workshop'
    | '/platform/create'
    | '/platform/officers'
    | '/platform/tenants'
    | '/principal/dashboard'
    | '/principal/heatmap'
    | '/principal/roi'
    | '/admin'
    | '/beo'
    | '/deo'
    | '/diet'
    | '/hod'
    | '/learner'
    | '/platform'
    | '/principal'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/completion'
    | '/admin/config'
    | '/admin/content'
    | '/admin/departments'
    | '/admin/maturity'
    | '/admin/overview'
    | '/admin/people'
    | '/admin/readiness'
    | '/beo/overview'
    | '/deo/overview'
    | '/diet/overview'
    | '/hod/analytics'
    | '/hod/dashboard'
    | '/learner/assessment'
    | '/learner/check'
    | '/learner/dashboard'
    | '/learner/learning'
    | '/learner/practice'
    | '/learner/sandbox'
    | '/learner/workshop'
    | '/platform/create'
    | '/platform/officers'
    | '/platform/tenants'
    | '/principal/dashboard'
    | '/principal/heatmap'
    | '/principal/roi'
    | '/admin/'
    | '/beo/'
    | '/deo/'
    | '/diet/'
    | '/hod/'
    | '/learner/'
    | '/platform/'
    | '/principal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminCompletionRoute: typeof AdminCompletionRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminMaturityRoute: typeof AdminMaturityRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminReadinessRoute: typeof AdminReadinessRoute
  BeoOverviewRoute: typeof BeoOverviewRoute
  DeoOverviewRoute: typeof DeoOverviewRoute
  DietOverviewRoute: typeof DietOverviewRoute
  HodAnalyticsRoute: typeof HodAnalyticsRoute
  HodDashboardRoute: typeof HodDashboardRoute
  LearnerAssessmentRoute: typeof LearnerAssessmentRoute
  LearnerCheckRoute: typeof LearnerCheckRoute
  LearnerDashboardRoute: typeof LearnerDashboardRoute
  LearnerLearningRoute: typeof LearnerLearningRoute
  LearnerPracticeRoute: typeof LearnerPracticeRoute
  LearnerSandboxRoute: typeof LearnerSandboxRoute
  LearnerWorkshopRoute: typeof LearnerWorkshopRoute
  PlatformCreateRoute: typeof PlatformCreateRoute
  PlatformOfficersRoute: typeof PlatformOfficersRoute
  PlatformTenantsRoute: typeof PlatformTenantsRoute
  PrincipalDashboardRoute: typeof PrincipalDashboardRoute
  PrincipalHeatmapRoute: typeof PrincipalHeatmapRoute
  PrincipalRoiRoute: typeof PrincipalRoiRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BeoIndexRoute: typeof BeoIndexRoute
  DeoIndexRoute: typeof DeoIndexRoute
  DietIndexRoute: typeof DietIndexRoute
  HodIndexRoute: typeof HodIndexRoute
  LearnerIndexRoute: typeof LearnerIndexRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  PrincipalIndexRoute: typeof PrincipalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/': {
      id: '/principal/'
      path: '/principal'
      fullPath: '/principal/'
      preLoaderRoute: typeof PrincipalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/': {
      id: '/learner/'
      path: '/learner'
      fullPath: '/learner/'
      preLoaderRoute: typeof LearnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/': {
      id: '/hod/'
      path: '/hod'
      fullPath: '/hod/'
      preLoaderRoute: typeof HodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet/': {
      id: '/diet/'
      path: '/diet'
      fullPath: '/diet/'
      preLoaderRoute: typeof DietIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deo/': {
      id: '/deo/'
      path: '/deo'
      fullPath: '/deo/'
      preLoaderRoute: typeof DeoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beo/': {
      id: '/beo/'
      path: '/beo'
      fullPath: '/beo/'
      preLoaderRoute: typeof BeoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/roi': {
      id: '/principal/roi'
      path: '/principal/roi'
      fullPath: '/principal/roi'
      preLoaderRoute: typeof PrincipalRoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/heatmap': {
      id: '/principal/heatmap'
      path: '/principal/heatmap'
      fullPath: '/principal/heatmap'
      preLoaderRoute: typeof PrincipalHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/dashboard': {
      id: '/principal/dashboard'
      path: '/principal/dashboard'
      fullPath: '/principal/dashboard'
      preLoaderRoute: typeof PrincipalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/tenants': {
      id: '/platform/tenants'
      path: '/platform/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof PlatformTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/officers': {
      id: '/platform/officers'
      path: '/platform/officers'
      fullPath: '/platform/officers'
      preLoaderRoute: typeof PlatformOfficersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/create': {
      id: '/platform/create'
      path: '/platform/create'
      fullPath: '/platform/create'
      preLoaderRoute: typeof PlatformCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/workshop': {
      id: '/learner/workshop'
      path: '/learner/workshop'
      fullPath: '/learner/workshop'
      preLoaderRoute: typeof LearnerWorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/sandbox': {
      id: '/learner/sandbox'
      path: '/learner/sandbox'
      fullPath: '/learner/sandbox'
      preLoaderRoute: typeof LearnerSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/practice': {
      id: '/learner/practice'
      path: '/learner/practice'
      fullPath: '/learner/practice'
      preLoaderRoute: typeof LearnerPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/learning': {
      id: '/learner/learning'
      path: '/learner/learning'
      fullPath: '/learner/learning'
      preLoaderRoute: typeof LearnerLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/dashboard': {
      id: '/learner/dashboard'
      path: '/learner/dashboard'
      fullPath: '/learner/dashboard'
      preLoaderRoute: typeof LearnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/check': {
      id: '/learner/check'
      path: '/learner/check'
      fullPath: '/learner/check'
      preLoaderRoute: typeof LearnerCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/assessment': {
      id: '/learner/assessment'
      path: '/learner/assessment'
      fullPath: '/learner/assessment'
      preLoaderRoute: typeof LearnerAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/dashboard': {
      id: '/hod/dashboard'
      path: '/hod/dashboard'
      fullPath: '/hod/dashboard'
      preLoaderRoute: typeof HodDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/analytics': {
      id: '/hod/analytics'
      path: '/hod/analytics'
      fullPath: '/hod/analytics'
      preLoaderRoute: typeof HodAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet/overview': {
      id: '/diet/overview'
      path: '/diet/overview'
      fullPath: '/diet/overview'
      preLoaderRoute: typeof DietOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deo/overview': {
      id: '/deo/overview'
      path: '/deo/overview'
      fullPath: '/deo/overview'
      preLoaderRoute: typeof DeoOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beo/overview': {
      id: '/beo/overview'
      path: '/beo/overview'
      fullPath: '/beo/overview'
      preLoaderRoute: typeof BeoOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/readiness': {
      id: '/admin/readiness'
      path: '/admin/readiness'
      fullPath: '/admin/readiness'
      preLoaderRoute: typeof AdminReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/admin/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/maturity': {
      id: '/admin/maturity'
      path: '/admin/maturity'
      fullPath: '/admin/maturity'
      preLoaderRoute: typeof AdminMaturityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/completion': {
      id: '/admin/completion'
      path: '/admin/completion'
      fullPath: '/admin/completion'
      preLoaderRoute: typeof AdminCompletionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminCompletionRoute: AdminCompletionRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminMaturityRoute: AdminMaturityRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminPeopleRoute: AdminPeopleRoute,
  AdminReadinessRoute: AdminReadinessRoute,
  BeoOverviewRoute: BeoOverviewRoute,
  DeoOverviewRoute: DeoOverviewRoute,
  DietOverviewRoute: DietOverviewRoute,
  HodAnalyticsRoute: HodAnalyticsRoute,
  HodDashboardRoute: HodDashboardRoute,
  LearnerAssessmentRoute: LearnerAssessmentRoute,
  LearnerCheckRoute: LearnerCheckRoute,
  LearnerDashboardRoute: LearnerDashboardRoute,
  LearnerLearningRoute: LearnerLearningRoute,
  LearnerPracticeRoute: LearnerPracticeRoute,
  LearnerSandboxRoute: LearnerSandboxRoute,
  LearnerWorkshopRoute: LearnerWorkshopRoute,
  PlatformCreateRoute: PlatformCreateRoute,
  PlatformOfficersRoute: PlatformOfficersRoute,
  PlatformTenantsRoute: PlatformTenantsRoute,
  PrincipalDashboardRoute: PrincipalDashboardRoute,
  PrincipalHeatmapRoute: PrincipalHeatmapRoute,
  PrincipalRoiRoute: PrincipalRoiRoute,
  AdminIndexRoute: AdminIndexRoute,
  BeoIndexRoute: BeoIndexRoute,
  DeoIndexRoute: DeoIndexRoute,
  DietIndexRoute: DietIndexRoute,
  HodIndexRoute: HodIndexRoute,
  LearnerIndexRoute: LearnerIndexRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  PrincipalIndexRoute: PrincipalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
